package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
	"github.com/sagudeloo/tutorial/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Experience)
// DB Table: Plural (experiences)
// Resource: Plural (Experiences)
// Path: Plural (/experiences)
// View Template Folder: Plural (/templates/experiences/)

// ExperiencesResource is the resource for the Experience model
type ExperiencesResource struct {
	buffalo.Resource
}

// List gets all Experiences. This function is mapped to the path
// GET /experiences
func (v ExperiencesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	experiences := &models.Experiences{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Experiences from the DB
	if err := q.All(experiences); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("experiences", experiences)
		return c.Render(http.StatusOK, r.HTML("/experiences/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(experiences))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(experiences))
	}).Respond(c)
}

// Show gets the data for one Experience. This function is mapped to
// the path GET /experiences/{experience_id}
func (v ExperiencesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Experience
	experience := &models.Experience{}

	// To find the Experience the parameter experience_id is used.
	if err := tx.Find(experience, c.Param("experience_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("experience", experience)

		return c.Render(http.StatusOK, r.HTML("/experiences/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(experience))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(experience))
	}).Respond(c)
}

// New renders the form for creating a new Experience.
// This function is mapped to the path GET /experiences/new
func (v ExperiencesResource) New(c buffalo.Context) error {
	c.Set("experience", &models.Experience{})

	return c.Render(http.StatusOK, r.HTML("/experiences/new.plush.html"))
}

// Create adds a Experience to the DB. This function is mapped to the
// path POST /experiences
func (v ExperiencesResource) Create(c buffalo.Context) error {
	// Allocate an empty Experience
	experience := &models.Experience{}

	// Bind experience to the html form elements
	if err := c.Bind(experience); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(experience)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("experience", experience)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/experiences/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "experience.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/experiences/%v", experience.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(experience))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(experience))
	}).Respond(c)
}

// Edit renders a edit form for a Experience. This function is
// mapped to the path GET /experiences/{experience_id}/edit
func (v ExperiencesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Experience
	experience := &models.Experience{}

	if err := tx.Find(experience, c.Param("experience_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("experience", experience)
	return c.Render(http.StatusOK, r.HTML("/experiences/edit.plush.html"))
}

// Update changes a Experience in the DB. This function is mapped to
// the path PUT /experiences/{experience_id}
func (v ExperiencesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Experience
	experience := &models.Experience{}

	if err := tx.Find(experience, c.Param("experience_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Experience to the html form elements
	if err := c.Bind(experience); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(experience)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("experience", experience)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/experiences/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "experience.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/experiences/%v", experience.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(experience))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(experience))
	}).Respond(c)
}

// Destroy deletes a Experience from the DB. This function is mapped
// to the path DELETE /experiences/{experience_id}
func (v ExperiencesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Experience
	experience := &models.Experience{}

	// To find the Experience the parameter experience_id is used.
	if err := tx.Find(experience, c.Param("experience_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(experience); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "experience.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/experiences")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(experience))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(experience))
	}).Respond(c)
}
